config/routes.rb
Rails.application.routes.draw do
  resources :titeks

end

app/models/titek.rb
class Titek < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/titeks_controller.rb
class TiteksController < ApplicationController
  before_action :set_titek, only: [:show, :edit, :update, :destroy]

  # GET /titeks
  # GET /titeks.json
  def index
    @titeks = Titek.all
  end

  # GET /titeks/1
  # GET /titeks/1.json
  def show
  end

  # GET /titeks/new
  def new
    @titek = Titek.new
  end

  # GET /titeks/1/edit
  def edit
  end

  # POST /titeks
  # POST /titeks.json
  def create
    @titek = Titek.new(titek_params)

    respond_to do |format|
      if @titek.save
        format.html { redirect_to @titek, notice: 'Titek was successfully created.' }
        format.json { render :show, status: :created, location: @titek }
      else
        format.html { render :new }
        format.json { render json: @titek.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /titeks/1
  # PATCH/PUT /titeks/1.json
  def update
    respond_to do |format|
      if @titek.update(titek_params)
        format.html { redirect_to @titek, notice: 'Titek was successfully updated.' }
        format.json { render :show, status: :ok, location: @titek }
      else
        format.html { render :edit }
        format.json { render json: @titek.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /titeks/1
  # DELETE /titeks/1.json
  def destroy
    @titek.destroy
    respond_to do |format|
      format.html { redirect_to titeks_url, notice: 'Titek was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_titek
      @titek = Titek.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def titek_params
      params[:titek]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/titeks_helper.rb
module TiteksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
  <title>Pamietnik</title>
      <%= stylesheet_link_tag "application", media: "all",
      "data-turbolinks-track" => true %>
      <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
      <%= csrf_meta_tags %>
  </head>
    <body>
 <nav class="navbar navbar-inverse navbar-fixed-top">
<div class="navbar-inner">

<a href="#" class="navbar-brand">Trolololo</a>

</div>
  </nav>
  <div class="container">
  <%= yield %>
  </div>
    </body>
</html>

app/views/titeks/_form.html.erb
<%= form_for(@titek) do |f| %>
  <% if @titek.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@titek.errors.count, "error") %> prohibited this titek from being saved:</h2>

      <ul>
      <% @titek.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/titeks/edit.html.erb
<h1>Editing Titek</h1>

<%= render 'form' %>

<%= link_to 'Show', @titek %> |
<%= link_to 'Back', titeks_path %>

app/views/titeks/index.html.erb
<div class="container">
  <h1> "Pamietnik Titka" </h1>  
  <h3> 'O życiu i perypetiach przyszłego mistrza'</h3>
</div>

app/views/titeks/new.html.erb
<h1>New Titek</h1>

<%= render 'form' %>

<%= link_to 'Back', titeks_path %>

app/views/titeks/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_titek_path(@titek) %> |
<%= link_to 'Back', titeks_path %>